name: Build Backend and Frontend

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
  workflow_dispatch:    

permissions:
  contents: read

jobs:
  build:
    name: Build All Projects
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        project:
          - src/Memofee/Memofee.csproj
          - src/Memofee.Client/Memofee.Client.csproj
          - src/Memofee.AppHost/Memofee.AppHost.csproj
          - src/Memofee.ServiceDefaults/Memofee.ServiceDefaults.csproj

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'preview'

      - name: Restore dependencies
        run: dotnet restore ${{ matrix.project }}

      - name: Build project
        run: dotnet build ${{ matrix.project }} --no-restore --configuration Release